name: thirteen_app
description: Thirteen card game

publish_to: "none"

version: 0.0.1+5

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  font_awesome_flutter: ">= 4.7.0"
  firebase_auth: ^3.3.7
  json_annotation: ^4.4.0
  nanoid: ^1.0.0
  intl: ^0.17.0
  cloud_functions: ^3.2.8
  go_router: ^3.0.3
  shared_preferences: ^2.0.13
  rxdart: ^0.27.3
  audioplayers: ^0.20.1
  flutter_riverpod: ^1.0.3
  mockito: ^5.1.0

dependency_overrides:
  font_awesome_flutter:
    path: fa/font_awesome_flutter

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  test: ^1.19.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets_dev/icon/icon.png"
  adaptive_icon_background: "#4CBC39"
  adaptive_icon_foreground: "assets_dev/icon/icon_adaptive.png"

flutter:
  uses-material-design: true

  assets:
    - assets/audio/start_game.wav
    - assets/audio/select_card.wav
    - assets/audio/play_card_success.wav
    - assets/audio/play_card_error.wav
    - assets/audio/game_lost.wav
    - assets/audio/game_win.wav

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
