// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PX5muRQ04hufZHtIwI1jM2LpBqvmvys',
    appId: '1:242888687377:web:fff639d7a01766e8d316b0',
    messagingSenderId: '242888687377',
    projectId: 'thirteen-app',
    authDomain: 'thirteen-app.firebaseapp.com',
    storageBucket: 'thirteen-app.appspot.com',
    measurementId: 'G-CBCC8L7C0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvuMB9lQ7Hx5aYuHZVXHRdgjWs6D75MHg',
    appId: '1:242888687377:android:f1a4297cfceb874bd316b0',
    messagingSenderId: '242888687377',
    projectId: 'thirteen-app',
    storageBucket: 'thirteen-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-30KKwosEW0ZVRHqD9YIbF6HTtbEMncQ',
    appId: '1:242888687377:ios:6fd7a372ce630047d316b0',
    messagingSenderId: '242888687377',
    projectId: 'thirteen-app',
    storageBucket: 'thirteen-app.appspot.com',
    iosClientId:
        '242888687377-9808fbv5grknpvskoskslr0pbuj4n4om.apps.googleusercontent.com',
    iosBundleId: 'com.danielkerwin.thirteen',
  );
}
