// Mocks generated by Mockito 5.1.0 from annotations
// in thirteen_app/test/game_filter_test.dart.
// Do not manually edit this file.

import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:thirteen_app/constants/game.constants.dart' as _i3;
import 'package:thirteen_app/providers/filter.provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Filter].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilter extends _i1.Mock implements _i2.Filter {
  MockFilter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set gameFilter(_i3.GameFilters? filter) =>
      super.noSuchMethod(Invocation.setter(#gameFilter, filter),
          returnValueForMissingStub: null);
  @override
  _i3.GameFilters get gameFilter =>
      (super.noSuchMethod(Invocation.getter(#gameFilter),
          returnValue: _i3.GameFilters.active) as _i3.GameFilters);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  void addListener(_i4.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i4.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
